server:
  port: 8102
spring:
  application:
    name: GXSHOPPING-PRODUCT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gxshopping-product?serverTimezone=GMT%2B8
    username: root
    password: root

#配置Mapper.xml文件位置
#mybatis-plus:
#  mapper-locations: classpath*:yahaha/gxshopping/mapper/*Mapper.xml
